### ISSUE TITLE
老哥 能不能写一个纯c++的demo啊。基于这东西 看都看不懂了

### ISSUE THREAD

**Issue by fengminxuan** [linuxvae/ngx_rtmp_http_flv_module#1]
ffmpeg不是可以推到tcp上，我接一下就行。为什么要用rtmp啊。网上全都是rtmp转http，看得头疼。

**Comment by linuxvae** [comment]
不好意思呀，主要是一般的直播都是基于网页h5播放，所以要使用h5中的video标签。tcp不能兼容，得使用http协议，rtmp就是基于tcp协议的。我改改 在加上一些说明和文件，能直接安装跑起来哈
